In [15]:
# Name : Taukir Shekh[19DCS134]
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.8.0


In [16]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [17]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [18]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.31862   , -0.70574456, -0.2691934 , -0.14307135, -0.04961446,
        -0.00126328, -0.28100854, -1.0866023 , -0.582705  , -0.57173216]],
      dtype=float32)

In [19]:
tf.nn.softmax(predictions).numpy()

array([[0.17940949, 0.06441241, 0.09966928, 0.11306688, 0.12414329,
        0.13029324, 0.0984986 , 0.04401139, 0.07284587, 0.0736496 ]],
      dtype=float32)

In [20]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [21]:
loss_fn(y_train[:1], predictions).numpy()

2.0379677

In [22]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [23]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2981 - accuracy: 0.9128
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1415 - accuracy: 0.9572
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1084 - accuracy: 0.9672
Epoch 4/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0889 - accuracy: 0.9720
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0749 - accuracy: 0.9765
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0657 - accuracy: 0.9792
Epoch 7/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0605 - accuracy: 0.9805
Epoch 8/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0542 - accuracy: 0.9822
Epoch 9/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0489 - accuracy: 0.9843
Epoch 10/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.047

In [24]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0705 - accuracy: 0.9785 - 455ms/epoch - 1ms/step


[0.0705399438738823, 0.9785000085830688]

In [27]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.56513503e-08, 2.09296536e-09, 4.87405146e-07, 1.78777209e-05,
        3.91827385e-13, 1.43847876e-08, 6.83276544e-16, 9.99980927e-01,
        3.59761376e-09, 6.73610884e-07],
       [1.26784389e-10, 1.46066432e-05, 9.99979973e-01, 3.03030242e-06,
        7.42535763e-15, 1.29444956e-07, 2.89207902e-09, 1.19269981e-14,
        2.28057252e-06, 3.28225741e-14],
       [5.70740177e-10, 9.99913335e-01, 2.34170693e-05, 4.07610230e-07,
        1.58573741e-07, 1.64845861e-08, 2.61326587e-08, 6.11738506e-05,
        1.37927225e-06, 1.05236146e-10],
       [9.98930991e-01, 2.07025197e-09, 1.21156563e-05, 2.55349492e-10,
        3.14561883e-04, 3.48445681e-08, 7.14120630e-04, 6.34875869e-06,
        9.95620475e-10, 2.16340322e-05],
       [3.38057646e-07, 1.14066903e-14, 7.11273231e-07, 1.89219995e-09,
        9.99896765e-01, 2.28730967e-09, 4.69248711e-08, 5.40916226e-05,
        1.51037334e-08, 4.80671115e-05]], dtype=float32)>

In [26]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.56513503e-08, 2.09296536e-09, 4.87405146e-07, 1.78777209e-05,
        3.91827385e-13, 1.43847876e-08, 6.83276544e-16, 9.99980927e-01,
        3.59761376e-09, 6.73610884e-07],
       [1.26784389e-10, 1.46066432e-05, 9.99979973e-01, 3.03030242e-06,
        7.42535763e-15, 1.29444956e-07, 2.89207902e-09, 1.19269981e-14,
        2.28057252e-06, 3.28225741e-14],
       [5.70740177e-10, 9.99913335e-01, 2.34170693e-05, 4.07610230e-07,
        1.58573741e-07, 1.64845861e-08, 2.61326587e-08, 6.11738506e-05,
        1.37927225e-06, 1.05236146e-10],
       [9.98930991e-01, 2.07025197e-09, 1.21156563e-05, 2.55349492e-10,
        3.14561883e-04, 3.48445681e-08, 7.14120630e-04, 6.34875869e-06,
        9.95620475e-10, 2.16340322e-05],
       [3.38057646e-07, 1.14066903e-14, 7.11273231e-07, 1.89219995e-09,
        9.99896765e-01, 2.28730967e-09, 4.69248711e-08, 5.40916226e-05,
        1.51037334e-08, 4.80671115e-05]], dtype=float32)>